import '../Style/globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}  >
      <header className='encabezado'>

          <nav className='menu'>
          <div className='title'>
            Parque Nacional Mochima
          </div>
            <ul className='lista'>
              <li>
                <Link style={{ textDecoration: "none" }} href={"./"}>
                  inicio
                </Link>
              </li>
              <li>
                <Link style={{ textDecoration: "none" }} href={"servicios"}>
                  servicios
                </Link>
              </li>
              <li>
                <Link style={{ textDecoration: "none" }} href={"/playas"}>
                  playas
                </Link>
              </li>
              <li>
                <Link style={{ textDecoration: "none" }} href={"masInformacion"}>
                  mas información
                </Link>
              </li>
            </ul>


          </nav>
        </header>
        {children}</body>
    </html>
  )
}
